# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17c7b56be75a13fa3839cf573ad5b3d126088552177595d68668ce94c42371fc6e74ed0e3279beb75fa41de5b6c8ee62b08f22e0faecb3c5a9dd43f88fc2a804

test:
  secret_key_base: c97b430c336c56d54719e3426c50a49d876446aeb3a4dfacdb675f2ab15426f1bda6ded3bca10fd4bbb8970c9c4b17b9146d9733619730a181b48d9cac833bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
